version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: soil
      POSTGRES_USER: soiluser
      POSTGRES_PASSWORD: soilpass
    ports:
      - "5432:5432"
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  backend-java:
    build: ./backend-java
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mosquitto
